INSERT INTO intents (intent, category, description) VALUES
('bathroom_reset', '시설문의', '화장실에 비누나 휴지가 비치되어 있지 않아요.'),
('report_printing_issue', '시설문의', '프린트기 위치나 사용이 불편해요.'),

('lms_reset', 'LMS 관련', '사이버강의 비밀번호 초기화 요청합니다!'),
('jeonbuk_lms', 'LMS 관련', '전북권역 LMS 로그인이 안돼요!'),
('lms_issue', 'LMS 관련', '사이버 강의 사이트에 오류가 발생했어요!'),
('lms_add_issue', 'LMS 관련', '사이버강의 인원 증원 요청합니다!'),
('ctl_timeline_inquiry', 'LMS 관련', '사이버강의 재생창 하단부가 안나와요!'),
('ctl_mobile_inquiry', 'LMS 관련', '사이버강의 모바일 수강 방법 알려주세요!'),
('ctl_mobile_attendance_inquiry', 'LMS 관련', '모바일로 강의 들었는데 출석은 어떻게 확인하나요?'),
('ctl_no_attendance_inquiry', 'LMS 관련', '사이버강의 수강했는데 출석 인정이 안돼요!'),
('ctl_no_culture', 'LMS 관련', '기업가정신과 창업의 이해 과목이 사이버강의 사이트에 안떠요!'),
('ctl_login_inquiry', 'LMS 관련', '사이버강의 로그인이 안돼요!'),
('ctl_tokeun_inquiry', 'LMS 관련', '토큰발급 횟수가 초과돼서 진행이 안돼요!'),
('ctl_popup_inquiry', 'LMS 관련', '응시하기 버튼을 클릭해도 시험 페이지로 안넘어가요!'),
('ctl_test_inquiry', 'LMS 관련', '시험 보는 도중 시험 창이 갑자기 꺼졌어요!'),
('ctl_cyber_lecture_inquiry', 'LMS 관련', '사이버강의는 어디서 수강하나요?'),


('attendance_reset', '출결문의', '출결 앱 비밀번호를 잊어버렸어요!'),
('inquire_attendance_appeal_period', '출결문의', '출결 이의 신청 기간과 출결 기준이 궁금해요!'),
('hope_attendance_inquiry', '출결문의', '희망디딤돌 출결 현황은 어떻게 확인하나요?'),

('inquire_withdrawal', '수강문의', '자퇴는 어떻게 하나요?'),
('retake_course_unavailable', '수강문의', '폐강된 과목은 어떻게 재수강 하나요?'),
('inquire_grade_cancellation', '수강문의', '이미 취득한 학점은 취소가 가능하나요?'),
('request_course_withdrawal', '수강문의', '수강철회 신청 방법이나 조건이 궁금해요!'),
('inquire_course_catalog', '수강문의', '수강 편람을 확인하고 싶어요!'),
('course_cancellation_inquiry', '수강문의', '폐강 공지는 어디서 확인하나요?'),
('request_class_capacity_increase', '수강문의', '수강 정원이 초과됐는데 추가로 받아주실 수 있나요?'),
('retake_the_course', '수강문의', '재수강 신청 방법이 궁금해요!'),
('course_no_registration_inquiry', '수강문의', '수강신청철회 방법과 기간이 궁금해요!'),

('request_enrollment_certificate', '증명서문의', '재학증명서를 온라인으로 발급받고 싶어요!'),
('request_completion_certificate', '증명서문의', '수료증명서를 발급받고 싶어요!'),
('achievement_inquiry', '증명서문의', '성적증명서를 발급받고 싶어요!'),
('student_ID_inquiry', '증명서문의', '학생증 재발급 받으려면 어떻게 해야 하나요?'),

('scholarship_inquiry', '장학금 관련', '장학금 관련 질문드립니다.'),
('hope_scholarship_inquiry', '장학금 관련', '희망사다리 장학금은 어떻게 지급되나요?'),

('leave_of_absence_inquiry', '학사행정 관련', '휴학신청은 어떻게 하나요?'),
('return_to_school_inquiry', '학사행정 관련', '복학신청은 어떻게 하나요?'),
('tuition_fee_inquiry', '학사행정 관련', '등록금 추가 납부 기간 알려주세요!'),
('inquire_employment_leave', '학사행정 관련', '취업계, 자율계 신청 방법이 궁금해요!'),
('graduation_issue', '학사행정 관련', '졸업식에 꼭 참여해야 하나요?'),
('inquire_rank_criteria', '학사행정 관련', '석차 기준은 어떻게 산정되나요?'),
('request_fee_refund', '학사행정 관련', '학생회비/학회비를 환불받고 싶어요!'),
('graduation_inquiry', '학사행정 관련', '졸업학점은 몇 학점인가요?'),
('academic_warning', '학사행정 관련', '학사경고 기준이나 처리 절차가 궁금해요!'),
('expulsion', '학사행정 관련', '제적되는 기준이 궁금해요!'),

('affairs_inquiry', '행정실문의', '교무처 연락처 알고싶어요!'),
('inquire_office_hours', '행정실문의', '학교 사무실 운영시간이 궁금해요!'),
('ask_ctl_website', '행정실문의', 'CTL 홈페이지 주소 알려주세요!'),
('office_inquiry', '행정실문의', '학교 오피스365는 어디서 이용할 수 있나요?'),
('ctl_tel', '행정실문의', '교수학습개발센터 전화번호가 궁금해요!'),

('bus_inquiry', '통학버스 관련', '통학버스 시간표는 어디서 보나요?'),

('howon_location', '캠퍼스 위치', '호원대학교 가는 길'),

('library_inquiry', '도서관 관련', '도서관 열람실 운영시간 궁금해요!'),

('post_office_inquiry', '우편/택배 관련', '교내에 우체국이 있나요?'),

('dormitory', '기숙사 관련', '기숙사비는 어떻게 납부하나요?'),

('inquire_student_email', '이메일 관련', '학생 이메일은 어디서 발급받나요?'),

('lost item_inquiry', '분실물 관련', '분실물은 어디에서 찾을 수 있나요?'),

('performance_media', '학과정보', '공연미디어학부 사무실 위치와 전화번호 알려주세요!'),
('applied_music', '학과정보', '실용음악과 사무실 위치와 전화번호 알려주세요!'),
('kpop', '학과정보', 'k-pop학과 사무실 위치와 전화번호 알려주세요!'),
('nursing', '학과정보', '간호학과 사무실 위치와 전화번호 알려주세요!'),
('physical_therapy', '학과정보', '물리치료학과 사무실 위치와 전화번호 알려주세요!'),
('emergency_rescue', '학과정보', '응급구조학과 사무실 위치와 전화번호 알려주세요!'),
('dental_hygiene', '학과정보', '치위생학과 사무실 위치와 전화번호 알려주세요!'),
('early_childhood_education', '학과정보', '유아교육과 사무실 위치와 전화번호 알려주세요!'),
('hotel_cooking', '학과정보', '호텔외식조리학과 사무실 위치와 전화번호 알려주세요!'),
('child_welfare', '학과정보', '아동복지학과 사무실 위치와 전화번호 알려주세요!'),
('sports', '학과정보', '스포츠무도학과 사무실 위치와 전화번호 알려주세요!'),
('management', '학과정보', '경영학과 사무실 위치와 전화번호 알려주세요!'),
('glocal_freedom', '학과정보', '글로컬자유전공학부 사무실 위치와 전화번호 알려주세요!'),
('computer', '학과정보', 'IT소프트웨어보안학과 사무실 위치와 전화번호 알려주세요!'),
('automotive_machinery', '학과정보', '자동차기계공학과 사무실 위치와 전화번호 알려주세요!'),
('k_beauty', '학과정보', 'K-뷰티소재학과 사무실 위치와 전화번호 알려주세요!'),
('k_food', '학과정보', 'K-푸드창업학과 사무실 위치와 전화번호 알려주세요!'),
('k_content', '학과정보', 'K-콘텐츠제작학과 사무실 위치와 전화번호 알려주세요!'),
('social_welfare', '학과정보', '사회복지상담학과 사무실 위치와 전화번호 알려주세요!'),
('health_care', '학과정보', '보건헬스케어학과 사무실 위치와 전화번호 알려주세요!'),
('glocal_tourism', '학과정보', '글로컬관광학과 사무실 위치와 전화번호 알려주세요!'),
('architectural_Interior', '학과정보', '건축인테리어학과 사무실 위치와 전화번호 알려주세요!'),
('electric_fire_safety', '학과정보', '전기소방안전학과 사무실 위치와 전화번호 알려주세요!'),
('refinement', '학과정보', '교양과 사무실 위치와 전화번호 알려주세요!'),

('pro_personal_inquiry', '기타', '교수님 전화번호 알려주실 수 있나요?'),
('e_inquiry', '기타', '군 E러닝 학점 상한선이 있나요?'),
('phone_number_inquiry', '기타', '교수님 연락처는 어디서 확인하나요?'),
('test_questions_inquiry', '기타', '시험에 출제되는 문제 개수를 확인하고 싶어요!'),
('ipad_test_inquiry', '기타', '아이패드를 이용해 시험에 응시할 수 있나요?'),
('whoareu', '기타', '챗봇 이름이 궁금해요!'),
('stress', '기타', '스트레스 받아요!'),
('sorry', '기타', '답변이 불만족이에요!'),
('song', '기타', '노래 추천해주세요!'),
('simsim', '기타', '심심해요!'),
('secret', '기타', '비밀이에요!'),
('seasonal_semester', '기타', '계절학기 수업 방식이나 일정이 궁금해요'),
('pubao', '기타', '푸바오?'),
('pizza', '기타', '피자 추천'),
('nono', '기타', '비속어'),
('movie', '기타', '영화 추천'),
('morning', '기타', '좋은 아침이에요!'),
('mom', '기타', '제작자가 궁금해요!'),
('luck', '기타', '행운'),
('love', '기타', '사랑해요!'),
('lol_patch', '기타', '롤 메타챔 추천'),
('honja', '기타', '혼자에요..'),
('hello', '기타', '안녕하세요!'),
('drink', '기타', '음료 추천'),
('drama', '기타', '드라마 추천'),
('dessert', '기타', '디저트 추천'),
('baegopa', '기타', '배고파요!'),



('trash', '알 수 없는 질문', ''),
('nlu_fallback', '알 수 없는 질문', '');